accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "bluechipChain"
  staking:
    unbonding_time: "1814400000000000"
    max_validators: "100"
    bond_denom: "bluechip"
  mint:
    params:
      mint_denom: "bluechip"
      blocks_per_year: "5256000"